# Generated by Django 5.1.6 on 2025-03-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_url', models.URLField()),
                ('fetch_method', models.CharField(choices=[('realtime', 'Real-Time'), ('queue', 'Queue')], default='queue', max_length=10)),
                ('auth_token', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('processed_data', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('processed', 'Processed')], default='raw', max_length=50)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.dataprovider')),
            ],
        ),
    ]
